import type { Lang } from '../i18n/languages'

// Ceremony Music Planner lead magnet (2026-09-24, docs/KEYWORD-MAP-2026-09.md § 9.3).
// The PDFs are generated by scripts/generate-ceremony-planner-pdf.mjs and committed to
// public/downloads/ — re-run that script after editing the planner copy.

export const ceremonyPlannerPath: Record<Lang, string> = {
	en: '/ceremony-music-planner/',
	id: '/id/ceremony-music-planner/',
}

export const ceremonyPlannerThankYouPath: Record<Lang, string> = {
	en: '/ceremony-music-planner/thank-you/',
	id: '/id/ceremony-music-planner/thank-you/',
}

export const ceremonyPlannerPdf: Record<Lang, string> = {
	en: '/downloads/allegra-ceremony-music-planner.pdf',
	id: '/downloads/allegra-ceremony-music-planner-id.pdf',
}

/** Journal slugs (EN slug, shared by the /id/ twin) that show the planner CTA below the article
 * body — ceremony-planning topics where an order-of-entrance / song-per-moment worksheet fits. */
export const ceremonyPlannerArticles = new Set([
	'wedding-processional-recessional-songs',
	'wedding-prelude-music',
	'wedding-ceremony-song-count',
	'wedding-ceremony-piano-music',
])
